version: "2"
services:
  zookeeper:
    image: jplock/zookeeper:3.4.11
    container_name: zookeeper
    ports:
      - 2181:2181

  kafka:
    image: ches/kafka:0.10.2.1
    container_name: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=${HOST_IP}
      - ZOOKEEPER_IP=${HOST_IP}
    ports:
      - 7203:7203
      - 9092:9092

  temp_kafka_producer:
    image: temp_kafka_producer:0.1
    container_name: temp_kafka
    environment:
      - KAFKA_HOST=${HOST_IP}
      - KAFKA_PORT=9092
    links:
      - mongo

  app:
    container_name: rest_server
    image: rest_server:0.1
    ports:
      - 8080:8080
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017